/**
 * Sitemap Generation
 * SEO Optimization: Dynamic sitemap for all pages
 * Performance: Cached and optimized for search engines
 *
 * Marketing pages removed 2026-04-04. URLs now derived from PAGE_SEO_CONFIG
 * (which tracks only pages that actually exist in the (landing) route group).
 */

import { MetadataRoute } from 'next';
import { SUPPORTED_LOCALES } from '@diboas/i18n/server';
import { SEO_DEFAULTS, PAGE_SEO_CONFIG } from '@/lib/seo/constants';

// Iteration 4 §3.6 (2026-05-15): `'market'` removed. Companion edits made
// below in PAGE_PRIORITIES + PATH_TO_OG_KEY. Page-level `noindex` meta is
// still gated by `NEXT_PUBLIC_MARKET_INDEXABLE` env var per iter-1 design;
// production flip happens in §3.8 of the iter-4 plan after calm-audit
// sign-off. Until that env-var flip, Google sees /market in sitemap but
// fetches it with `noindex` meta → no indexing.
const NOINDEX_PAGES = new Set(['demo', 'dream-mode', 'share']);

const PAGE_PRIORITIES: Record<string, number> = {
  '/': 1.0,
  '/business': 0.9,
  '/strategies': 0.9,
  '/about': 0.8,
  '/protocols': 0.8,
  '/learn': 0.8,
  '/learn/compound-interest': 0.8,
  // Phase 6C — Money Tools (Tier 1)
  '/tools': 0.8,
  '/tools/compound-interest': 0.8,
  '/tools/retirement': 0.8,
  '/tools/emergency-fund': 0.8,
  '/tools/goal-savings': 0.8,
  // Phase 6D — Money Tools (Tier 2)
  '/tools/inflation-impact': 0.8,
  '/tools/time-to-target': 0.8,
  '/tools/currency-depreciation': 0.8,
  // Phase 6E — Money Tools (Tier 3 B2B)
  '/tools/card-fees': 0.8,
  '/tools/idle-cash': 0.8,
  // Phase E (2026-05-16) — Asset history retrospective tool
  '/tools/asset-history': 0.8,
  // Iteration 4 (2026-05-15) — Adelaide Daily (/market)
  // Priority 0.7 places it alongside primary user destinations (/help,
  // /security) but below feature-tree roots (0.8 tools, 0.9 b2b).
  '/market': 0.7,
  '/help': 0.7,
  '/security': 0.7,
  // Investor vertical — public page only (the /investor-room is noindex and
  // intentionally excluded from the sitemap).
  '/investors': 0.6,
  '/legal/terms': 0.3,
  '/legal/privacy': 0.3,
  '/legal/cookies': 0.3,
};

/**
 * Map a sitemap path to its OG-image template key. Used to populate the
 * `images:` field on each entry so Google Image Search can index the
 * page-specific OG art generated by `apps/web/src/app/api/og/[page]/route.tsx`.
 *
 * Paths not listed here fall back to the `default` template.
 *
 * Phase 3 L4 (audit/2026-05-08): closes the image-sitemap gap surfaced in
 * the 2026-05-07 audit.
 */
const PATH_TO_OG_KEY: Record<string, string> = {
  '/': 'b2c',
  '/business': 'b2b',
  '/strategies': 'strategies',
  '/about': 'about',
  '/protocols': 'protocols',
  '/help': 'help',
  '/security': 'security',
  // Phase 6C — Money Tools. Each tool gets a dedicated OG image key under
  // `/api/og/<key>`. v1 falls back to `default` until 6F.2 ships per-tool art;
  // these stable keys ensure the sitemap is correct now and the renderer can
  // attach bespoke art later without sitemap churn.
  '/tools': 'tools',
  '/tools/compound-interest': 'tools-compound-interest',
  '/tools/retirement': 'tools-retirement',
  '/tools/emergency-fund': 'tools-emergency-fund',
  '/tools/goal-savings': 'tools-goal-savings',
  // Phase 6D — Tier 2 OG keys
  '/tools/inflation-impact': 'tools-inflation-impact',
  '/tools/time-to-target': 'tools-time-to-target',
  '/tools/currency-depreciation': 'tools-currency-depreciation',
  // Phase 6E — Tier 3 B2B OG keys
  '/tools/card-fees': 'tools-card-fees',
  '/tools/idle-cash': 'tools-idle-cash',
  // Phase E — Asset history OG key
  '/tools/asset-history': 'tools-asset-history',
  // Iteration 4 §3.6 — Adelaide Daily. Path B static OG (§6.3 locked):
  // registered in `lib/og/templates.tsx` PAGE_CONFIGS.market; renders via
  // the shared `/api/og/[page]/route.tsx` (zero new chunks).
  '/market': 'market',
};

function getAllUrls(): string[] {
  const urls: string[] = ['/'];

  Object.keys(PAGE_SEO_CONFIG).forEach((pageKey) => {
    if (pageKey !== 'home' && !NOINDEX_PAGES.has(pageKey)) {
      urls.push(`/${pageKey}`);
    }
  });

  // Investor vertical: the public page is indexed; the /investor-room (its own
  // route group, noindex) is never added here.
  if (!urls.includes('/investors')) {
    urls.push('/investors');
  }

  return urls;
}

/**
 * Build a fully-qualified URL for a given locale + path.
 *
 * Phase 3 L4 (audit/2026-05-08): replaces an earlier `replace(/\/+/g, '/')`
 * pass that incorrectly collapsed `https://` to `https:/`, breaking every
 * sitemap URL. We now build the path side cleanly and join with the base
 * URL at the end, leaving the protocol untouched.
 */
function buildLocalizedUrl(baseUrl: string, locale: string, path: string): string {
  // SEO-7: prefix EVERY locale, including English. Locale-less paths 307-redirect
  // to `/en/…` (middleware), and every page self-canonicalises to the prefixed
  // form (`generateCanonicalUrl`, the home `/${locale}` canonical, and the i18n
  // `generateAlternateUrls` helper). An unprefixed English `<loc>` + `en`
  // hreflang would advertise redirecting URLs that disagree with the canonicals.
  const localeSegment = `/${locale}`;
  const normalizedPath = path === '/' ? '' : path;
  // `${baseUrl}` has no trailing slash (per SEO_DEFAULTS); `localeSegment` is
  // `/xx`; `normalizedPath` starts with '/' (or is empty).
  return `${baseUrl}${localeSegment}${normalizedPath}` || baseUrl;
}

function getOgImageUrl(baseUrl: string, path: string): string {
  const ogKey = PATH_TO_OG_KEY[path] ?? 'default';
  return `${baseUrl}/api/og/${ogKey}`;
}

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = SEO_DEFAULTS.siteUrl.replace(/\/+$/, '');
  const urls = getAllUrls();
  const currentDate = new Date();

  const sitemapEntries: MetadataRoute.Sitemap = [];

  urls.forEach((url) => {
    const ogImageUrl = getOgImageUrl(baseUrl, url);

    SUPPORTED_LOCALES.forEach((locale) => {
      const fullUrl = buildLocalizedUrl(baseUrl, locale, url);

      sitemapEntries.push({
        url: fullUrl,
        lastModified: currentDate,
        changeFrequency: url === '/' ? 'daily' : 'weekly',
        priority: PAGE_PRIORITIES[url] ?? 0.5,
        // OG image URL is locale-agnostic (the templates render English copy
        // currently); per-locale OG variants would be a future enhancement.
        images: [ogImageUrl],
        alternates: {
          languages: SUPPORTED_LOCALES.reduce(
            (acc, lang) => {
              acc[lang] = buildLocalizedUrl(baseUrl, lang, url);
              return acc;
            },
            {} as Record<string, string>
          ),
        },
      });
    });
  });

  return sitemapEntries;
}
