/**
 * Protocols Page - Static Data
 *
 * All 26 DeFi protocols organized by category
 * Data is static and extracted for maintainability
 */

import type { ProtocolCategory } from './types';

/**
 * All protocols organized by category
 */
export const PROTOCOL_DATA: ProtocolCategory[] = [
  {
    id: 'lending',
    protocols: [
      {
        id: 'aave',
        name: 'Aave V3',
        description: 'The largest lending protocol in DeFi. You deposit assets, earn interest from borrowers, and can withdraw anytime.',
        founded: '2017 (V3: 2022)',
        tvl: '~$35 billion',
        blockchains: 'Ethereum, Arbitrum, Polygon, + 15 more',
        audits: '30+ audits',
        regulatory: 'SEC closed investigation without charges (Dec 2025)',
        website: 'https://aave.com',
        twitter: 'https://x.com/AaveAave',
      },
      {
        id: 'compound',
        name: 'Compound V3',
        description: 'Algorithmic money market where you earn interest by lending your crypto to borrowers.',
        founded: '2018 (V3: 2022)',
        tvl: '~$2 billion',
        blockchains: 'Ethereum, Arbitrum, Base, Polygon',
        audits: '4+ audits',
        regulatory: 'Decentralized protocol, no specific licenses required',
        website: 'https://compound.finance',
        twitter: 'https://x.com/compoundfinance',
      },
      {
        id: 'kamino',
        name: 'Kamino',
        description: "Solana's all-in-one DeFi platform combining lending, automated liquidity, and leverage.",
        founded: '2022',
        tvl: '~$2.5 billion',
        blockchains: 'Solana',
        audits: 'Multiple audits by OtterSec',
        regulatory: 'Decentralized protocol',
        website: 'https://kamino.finance',
        twitter: 'https://x.com/KaminoFinance',
      },
      {
        id: 'morpho',
        name: 'Morpho',
        description: 'Optimized lending that matches lenders directly with borrowers for better rates than traditional pools.',
        founded: '2022',
        tvl: '~$7 billion',
        blockchains: 'Ethereum, Base, Arbitrum',
        audits: '23+ audits',
        regulatory: 'First protocol used by Coinbase for bitcoin-backed loans',
        website: 'https://morpho.org',
        twitter: 'https://x.com/MorphoLabs',
      },
      {
        id: 'spark',
        name: 'Spark Protocol',
        description: "Lending protocol built on Aave's code, connected to Sky/MakerDAO's deep liquidity reserves.",
        founded: '2023',
        tvl: '~$4 billion',
        blockchains: 'Ethereum, Base, Arbitrum',
        audits: '7+ audits',
        regulatory: "Benefits from MakerDAO's 10+ year compliance history",
        website: 'https://spark.fi',
        twitter: 'https://x.com/sparkdotfi',
      },
      {
        id: 'fluid',
        name: 'Fluid',
        description: 'Next-generation lending combining features from Aave, Compound, and Uniswap with very low liquidation penalties.',
        founded: '2024',
        tvl: '~$2 billion',
        blockchains: 'Ethereum, Arbitrum, Base',
        audits: '3+ audits',
        regulatory: 'Built by Instadapp team (6+ years in DeFi)',
        website: 'https://fluid.io',
        twitter: 'https://x.com/0xFluid',
      },
    ],
  },
  {
    id: 'staking',
    protocols: [
      {
        id: 'lido',
        name: 'Lido Finance',
        description: 'Stake your ETH and receive stETH tokens you can use elsewhere while still earning staking rewards.',
        founded: '2020',
        tvl: '~$27 billion',
        blockchains: 'Ethereum, Polygon',
        audits: '20+ audits',
        regulatory: 'SEC clarified liquid staking is not a security (2025)',
        website: 'https://lido.fi',
        twitter: 'https://x.com/LidoFinance',
      },
      {
        id: 'rocketpool',
        name: 'Rocket Pool',
        description: 'Decentralized Ethereum staking that lets you stake with as little as 0.01 ETH.',
        founded: '2016 (mainnet 2021)',
        tvl: '~$2 billion',
        blockchains: 'Ethereum',
        audits: '5+ audits',
        regulatory: 'SEC confirmed rETH is not a security (Aug 2025)',
        website: 'https://rocketpool.net',
        twitter: 'https://x.com/Rocket_Pool',
      },
      {
        id: 'jito',
        name: 'Jito',
        description: 'Solana liquid staking that earns both staking rewards and MEV (trading) rewards.',
        founded: '2022',
        tvl: '~$2.8 billion',
        blockchains: 'Solana',
        audits: 'Multiple audits by Certora, OtterSec',
        regulatory: 'JitoSOL deemed non-security by SEC (March 2025)',
        website: 'https://jito.network',
        twitter: 'https://x.com/jikitonetwork',
      },
      {
        id: 'marinade',
        name: 'Marinade Finance',
        description: 'Non-custodial Solana staking across 100+ validators for better decentralization and rewards.',
        founded: '2021',
        tvl: '~$550 million',
        blockchains: 'Solana',
        audits: '5+ audits',
        regulatory: 'SOC 2 Type I & II certified — institutional-grade compliance',
        hasSuccess: true,
        website: 'https://marinade.finance',
        twitter: 'https://x.com/MarinadeFinance',
      },
      {
        id: 'sanctum',
        name: 'Sanctum',
        description: 'Unified liquidity layer for all Solana staking tokens, enabling instant swaps between different staked assets.',
        founded: '2021',
        tvl: '~$1.7 billion',
        blockchains: 'Solana',
        audits: 'Audited by Accretion',
        regulatory: 'Singapore-based, powering Binance and Bybit staking',
        website: 'https://sanctum.so',
        twitter: 'https://x.com/sanctumso',
      },
      {
        id: 'eigenlayer',
        name: 'EigenLayer',
        description: 'Restaking protocol that lets you use your staked ETH to secure additional applications and earn extra rewards.',
        founded: '2023',
        tvl: '~$12 billion',
        blockchains: 'Ethereum',
        audits: 'Multiple audits',
        regulatory: '$2M bug bounty program on Immunefi',
        website: 'https://eigenlayer.xyz',
        twitter: 'https://x.com/eigenlayer',
      },
    ],
  },
  {
    id: 'stablecoins',
    protocols: [
      {
        id: 'sky',
        name: 'Sky Protocol (formerly MakerDAO)',
        description: 'The original DeFi protocol. Deposit crypto as collateral, mint USDS/DAI stablecoins, earn savings rate.',
        founded: '2014',
        tvl: '~$6 billion',
        blockchains: 'Ethereum',
        audits: '10+ audits',
        regulatory: '10+ years operating, survived every market crash since 2017',
        website: 'https://sky.money',
        twitter: 'https://x.com/SkyEcosystem',
      },
      {
        id: 'ethena',
        name: 'Ethena',
        description: 'Creates USDe synthetic dollar through hedged positions, offering higher yields than traditional stablecoins.',
        founded: '2023',
        tvl: '~$6.5 billion',
        blockchains: 'Ethereum + 23 chains',
        audits: '7+ audits',
        regulatory: 'Exited German market after BaFin review; operates via BVI',
        hasWarning: true,
        website: 'https://ethena.fi',
        twitter: 'https://x.com/ethena_labs',
      },
      {
        id: 'ondo',
        name: 'Ondo Finance',
        description: 'Brings real-world assets on-chain — US Treasuries, bonds, and stocks as crypto tokens.',
        founded: '2021',
        tvl: '~$1.7 billion',
        blockchains: 'Ethereum, Solana, Arbitrum',
        audits: '4+ audits',
        regulatory: 'SEC-registered broker-dealer license via Oasis Pro acquisition',
        hasSuccess: true,
        website: 'https://ondo.finance',
        twitter: 'https://x.com/ondofinance',
      },
    ],
  },
  {
    id: 'yield',
    protocols: [
      {
        id: 'pendle',
        name: 'Pendle Finance',
        description: 'Separates yield from principal so you can trade, lock in, or speculate on future yields.',
        founded: '2021',
        tvl: '~$4.5 billion',
        blockchains: 'Ethereum, Arbitrum, BNB Chain',
        audits: '6+ audits',
        regulatory: '$250K bug bounty, Safe Harbor Agreement',
        website: 'https://pendle.finance',
        twitter: 'https://x.com/pendle_fi',
      },
      {
        id: 'yearn',
        name: 'Yearn Finance',
        description: 'Automated yield farming that moves your money between protocols to maximize returns.',
        founded: '2020',
        tvl: '~$500 million',
        blockchains: 'Ethereum, Arbitrum, Fantom',
        audits: '6+ audits',
        regulatory: 'Pioneer of yield aggregation, 5+ years operating',
        website: 'https://yearn.fi',
        twitter: 'https://x.com/yeaborfinance',
      },
      {
        id: 'curve',
        name: 'Curve Finance',
        description: 'Specialized exchange for stablecoins and similar assets with minimal slippage.',
        founded: '2020',
        tvl: '~$2.2 billion',
        blockchains: 'Ethereum + 20 chains',
        audits: '15+ audits',
        regulatory: "July 2023: $70M exploit (73% recovered) — Vyper compiler bug, not Curve's code",
        hasWarning: true,
        website: 'https://curve.finance',
        twitter: 'https://x.com/CurveFinance',
      },
      {
        id: 'convex',
        name: 'Convex Finance',
        description: 'Boosts your Curve rewards without needing to lock tokens for years.',
        founded: '2021',
        tvl: '~$1.5 billion',
        blockchains: 'Ethereum, Arbitrum',
        audits: '7 audits',
        regulatory: 'No exploits in 4 years; critical vulnerability found and patched in 2022 (no funds lost)',
        website: 'https://convexfinance.com',
        twitter: 'https://x.com/ConvexFinance',
      },
    ],
  },
  {
    id: 'perpetuals',
    protocols: [
      {
        id: 'gmx',
        name: 'GMX V2',
        description: 'Decentralized perpetual exchange. You provide liquidity, traders pay you fees.',
        founded: '2021',
        tvl: '~$400 million',
        blockchains: 'Arbitrum, Avalanche, Solana',
        audits: '10+ audits',
        regulatory: '$5M bug bounty on Immunefi',
        website: 'https://gmx.io',
        twitter: 'https://x.com/GMX_IO',
      },
      {
        id: 'jupiter',
        name: 'Jupiter JLP',
        description: "Solana's leading perpetual exchange. Provide liquidity, earn 70% of all trading fees.",
        founded: '2021 (perps 2023)',
        tvl: '~$1.6 billion',
        blockchains: 'Solana',
        audits: '6+ audits',
        regulatory: '$137M+ paid to liquidity providers since Jan 2024',
        website: 'https://jup.ag',
        twitter: 'https://x.com/JupiterExchange',
      },
      {
        id: 'drift',
        name: 'Drift Protocol',
        description: 'Full-featured trading platform on Solana with perpetuals, spot, and lending.',
        founded: '2021',
        tvl: '~$850 million',
        blockchains: 'Solana',
        audits: '3+ audits by Trail of Bits, OtterSec',
        regulatory: 'Open-source, real-time risk monitoring',
        website: 'https://drift.trade',
        twitter: 'https://x.com/DriftProtocol',
      },
    ],
  },
  {
    id: 'dex',
    protocols: [
      {
        id: 'raydium',
        name: 'Raydium',
        description: "Solana's main DEX with automated market making, concentrated liquidity, and token launches.",
        founded: '2021',
        tvl: '~$2 billion',
        blockchains: 'Solana',
        audits: '4+ audits',
        regulatory: 'Nov 2022: $4.4M exploit (admin key issue, users reimbursed)',
        hasWarning: true,
        website: 'https://raydium.io',
        twitter: 'https://x.com/RaydiumProtocol',
      },
      {
        id: 'orca',
        name: 'Orca',
        description: 'User-friendly Solana DEX known for clean design and efficient swaps.',
        founded: '2021',
        tvl: '~$400 million',
        blockchains: 'Solana',
        audits: '6+ audits',
        regulatory: 'No exploits in 4+ years; praised for code quality',
        website: 'https://orca.so',
        twitter: 'https://x.com/orca_so',
      },
      {
        id: 'balancer',
        name: 'Balancer',
        description: 'Programmable liquidity pools that can hold multiple tokens in custom ratios.',
        founded: '2020',
        tvl: '~$700 million',
        blockchains: 'Ethereum, Arbitrum, Polygon',
        audits: '11+ audits',
        regulatory: 'Nov 2025: $128M V2 exploit; V3 unaffected',
        hasWarning: true,
        website: 'https://balancer.fi',
        twitter: 'https://x.com/Balancer',
      },
    ],
  },
  {
    id: 'rwa',
    protocols: [
      {
        id: 'huma',
        name: 'Huma Finance',
        description: 'Instant cross-border payments and trade financing using crypto rails.',
        founded: '2022',
        tvl: '~$100 million',
        blockchains: 'Solana, Stellar, Polygon',
        audits: '6+ audits',
        regulatory: 'Partners with Circle, Stellar Development Foundation',
        website: 'https://huma.finance',
        twitter: 'https://x.com/humafinance',
      },
    ],
  },
];
