/**
 * Dream Mode - Constants
 *
 * Configuration constants for Dream Mode calculations and display
 * Data sourced from DeFiLlama historical analysis (May 2022 - Dec 2025)
 */

import type { DreamPath, DreamTimeframe, PathConfig, RegionalDisclaimer } from './types';

/**
 * Bank comparison rate (ECB Statistics, December 2024)
 * Average EU savings account rate
 */
export const BANK_APY_RATE = 0.5; // 0.5% APY

/**
 * ECB source citation for CLO compliance
 */
export const ECB_SOURCE_CITATION = {
  rate: BANK_APY_RATE,
  source: 'ECB Statistics',
  date: 'December 2024',
  url: 'https://www.ecb.europa.eu/stats/',
} as const;

/**
 * Timeframe configurations in days
 */
export const TIMEFRAME_DAYS: Record<DreamTimeframe, number> = {
  '1_week': 7,
  '1_month': 30,
  '1_year': 365,
  '5_years': 1825,
} as const;

/**
 * Path icon configuration
 */
export const PATH_ICONS: Record<DreamPath, string> = {
  safety: '🛡️',
  balance: '⚖️',
  growth: '🚀',
} as const;

/**
 * Path color configuration (for UI)
 */
export const PATH_COLORS: Record<DreamPath, { primary: string; secondary: string }> = {
  safety: { primary: '#3B82F6', secondary: '#60A5FA' },   // Blue
  balance: { primary: '#8B5CF6', secondary: '#A78BFA' },  // Purple
  growth: { primary: '#EF4444', secondary: '#F87171' },   // Red
} as const;

/**
 * Path configurations with multipliers from historical data
 * Source: DeFiLlama data analysis (May 2022 - December 2025)
 * Values from dream_mode_data.json generated by analytics
 */
export const PATH_CONFIGS: Record<DreamPath, PathConfig> = {
  safety: {
    id: 'safety',
    icon: '🛡️',
    avgApy: 0.9,
    maxDrawdown: 0.0,
    probabilityOfLoss: 0.5,
    strategies: [1, 3, 5, 7, 9],
    projections: {
      '1_week': { multiplier: 1.0002 },
      '1_month': { multiplier: 1.0007 },
      '1_year': { multiplier: 1.0086 },
      '5_years': { multiplier: 1.0438 },
    },
  },
  balance: {
    id: 'balance',
    icon: '⚖️',
    avgApy: 23.2,
    maxDrawdown: 37.2,
    probabilityOfLoss: 39.9,
    strategies: [2, 4, 6],
    projections: {
      '1_week': { multiplier: 1.004 },
      '1_month': { multiplier: 1.0173 },
      '1_year': { multiplier: 1.2321 },
      '5_years': { multiplier: 2.8398 },
    },
  },
  growth: {
    id: 'growth',
    icon: '🚀',
    avgApy: 64.2,
    maxDrawdown: 70.2,
    probabilityOfLoss: 55.7,
    strategies: [8, 10],
    warning: 'High volatility — up to 70% drawdown observed in historical testing',
    projections: {
      '1_week': { multiplier: 1.0096 },
      '1_month': { multiplier: 1.0416 },
      '1_year': { multiplier: 1.6422 },
      '5_years': { multiplier: 11.9447 },
    },
  },
} as const;

/**
 * Regional disclaimer configuration for CLO compliance
 */
export const REGIONAL_DISCLAIMERS: Record<string, RegionalDisclaimer> = {
  EU: {
    region: 'EU',
    primaryKey: 'dreamMode.disclaimer.body',
    cardKey: 'dreamMode.disclaimer.card',
  },
  US: {
    region: 'US',
    primaryKey: 'dreamMode.disclaimer.body',
    enhancedKey: 'dreamMode.disclaimer.enhanced.us',
    cardKey: 'dreamMode.disclaimer.card',
  },
  BRAZIL: {
    region: 'BRAZIL',
    primaryKey: 'dreamMode.disclaimer.body',
    enhancedKey: 'dreamMode.disclaimer.enhanced.brazil',
    cardKey: 'dreamMode.disclaimer.card',
  },
} as const;

/**
 * Amount slider configuration
 * Per CMO v2 spec: min €50, max €10,000, step €10, default €500
 */
export const AMOUNT_SLIDER_CONFIG = {
  min: 50,
  max: 10000,
  step: 10,
  default: 500,
  currency: '€',
} as const;

/**
 * Dream Mode analytics events
 */
export const DREAM_MODE_EVENTS = {
  STARTED: 'dream_mode_started',
  DISCLAIMER_ACCEPTED: 'dream_disclaimer_accepted',
  PATH_SELECTED: 'dream_path_selected',
  AMOUNT_SET: 'dream_amount_set',
  TIMEFRAME_CHANGED: 'dream_timeframe_changed',
  SIMULATION_STARTED: 'dream_simulation_started',
  SIMULATION_COMPLETED: 'dream_simulation_completed',
  SHARE_INITIATED: 'dream_share_initiated',
  SHARE_COMPLETED: 'dream_share_completed',
  CARD_DOWNLOADED: 'dream_card_downloaded',
  LINK_COPIED: 'dream_link_copied',
  PATH_RETRY: 'dream_path_retry',
  COMPLETED: 'dream_mode_completed',
} as const;

/**
 * Session storage keys for CLO compliance
 */
export const STORAGE_KEYS = {
  DISCLAIMER_ACCEPTED: 'dream_disclaimer_accepted',
  DISCLAIMER_TIMESTAMP: 'dream_disclaimer_timestamp',
  SELECTED_PATH: 'dream_selected_path',
} as const;
