/**
 * The Sandbox's single icon door (build rule: LucideIcon only, never raw
 * lucide-react imports scattered through components, never emoji as icons).
 * Named imports keep the bundle tree-shaken.
 */

import {
  ArrowLeft,
  ArrowRight,
  ArrowRightLeft,
  BarChart3,
  Bell,
  BookOpen,
  EyeOff,
  Briefcase,
  Calendar,
  Car,
  Coins,
  DollarSign,
  Check,
  ChevronLeft,
  ChevronRight,
  Clock,
  FastForward,
  FlaskConical,
  Gift,
  GitBranch,
  Globe,
  Lock,
  Mail,
  Megaphone,
  Moon,
  Sun,
  Percent,
  Upload,
  Users,
  GraduationCap,
  Heart,
  Home,
  Info,
  KeyRound,
  List,
  Pause,
  Pencil,
  Plane,
  Play,
  Plus,
  Receipt,
  Repeat,
  Shield,
  ShieldCheck,
  Sprout,
  Target,
  TreePalm,
  TrendingUp,
  User,
  Wallet,
  X,
  Zap,
  type LucideIcon as LucideIconType,
  TrendingDown,
  History,
  Minus,
  Eye,
  SlidersHorizontal,
} from 'lucide-react';

const ICONS: Record<string, LucideIconType> = {
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-right-left': ArrowRightLeft,
  'bar-chart': BarChart3,
  bell: Bell,
  calendar: Calendar,
  coins: Coins,
  'dollar-sign': DollarSign,
  'book-open': BookOpen,
  'eye-off': EyeOff,
  briefcase: Briefcase,
  car: Car,
  check: Check,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  history: History,
  minus: Minus,
  sliders: SlidersHorizontal,
  eye: Eye,
  clock: Clock,
  lock: Lock,
  mail: Mail,
  megaphone: Megaphone,
  moon: Moon,
  sun: Sun,
  percent: Percent,
  upload: Upload,
  users: Users,
  'fast-forward': FastForward,
  flask: FlaskConical,
  gift: Gift,
  'git-branch': GitBranch,
  globe: Globe,
  'graduation-cap': GraduationCap,
  heart: Heart,
  home: Home,
  info: Info,
  key: KeyRound,
  list: List,
  pause: Pause,
  pencil: Pencil,
  plane: Plane,
  play: Play,
  plus: Plus,
  receipt: Receipt,
  repeat: Repeat,
  shield: Shield,
  'shield-check': ShieldCheck,
  sprout: Sprout,
  target: Target,
  palmtree: TreePalm,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  user: User,
  wallet: Wallet,
  x: X,
  zap: Zap,
};

export type IconName = keyof typeof ICONS;

export function LucideIcon({
  name,
  size = 20,
  className,
}: {
  name: string;
  size?: number;
  className?: string;
}) {
  const Icon = ICONS[name] ?? Sprout;
  return <Icon size={size} className={className} aria-hidden />;
}

/** Every registered name — exported so a guard test can prove no call site
 *  falls through to the `?? Sprout` default with the wrong picture. */
export const ICON_NAMES: string[] = Object.keys(ICONS);
